require: rubocop-rails

AllCops:
  Exclude:
    - db/*
    - config/**/*
    - node_modules/**/*
    - bin/**/*

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['(\A|\s)#']

Style/Documentation:
  Enabled: False