language: ruby
rvm:
  - 2.6.2
services:
  - postgresql
install:
  - bundle install
before_script:
  - psql -c 'create database businesska_test;' -U postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rspec